2023-10-13 16:17:35.143 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli

2023-10-13 16:17:35.143 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 16:17:35.169 [info] [Error - 16:17:35] Server initialization failed.
2023-10-13 16:17:35.169 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.169 [info] [Info  - 16:17:35] Connection to server got closed. Server will restart.
2023-10-13 16:17:35.170 [info] true
2023-10-13 16:17:35.170 [info] [Error - 16:17:35] Python Jedi client: couldn't create connection to server.
2023-10-13 16:17:35.170 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.189 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli

2023-10-13 16:17:35.189 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 16:17:35.192 [info] [Error - 16:17:35] Server initialization failed.
2023-10-13 16:17:35.192 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.192 [info] [Info  - 16:17:35] Connection to server got closed. Server will restart.
2023-10-13 16:17:35.192 [info] true
2023-10-13 16:17:35.192 [info] [Error - 16:17:35] Python Jedi client: couldn't create connection to server.
2023-10-13 16:17:35.192 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.227 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-13 16:17:35.227 [info]     from jedi_language_server.cli import cli

2023-10-13 16:17:35.227 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 16:17:35.231 [info] [Error - 16:17:35] Server initialization failed.
2023-10-13 16:17:35.231 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.231 [info] [Info  - 16:17:35] Connection to server got closed. Server will restart.
2023-10-13 16:17:35.231 [info] true
2023-10-13 16:17:35.231 [info] [Error - 16:17:35] Python Jedi client: couldn't create connection to server.
2023-10-13 16:17:35.231 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.231 [info] [Error - 16:17:35] Restarting server failed
2023-10-13 16:17:35.231 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.246 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-13 16:17:35.246 [info]     from jedi_language_server.cli import cli

2023-10-13 16:17:35.247 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 16:17:35.249 [info] [Error - 16:17:35] Server initialization failed.
2023-10-13 16:17:35.249 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.249 [info] [Info  - 16:17:35] Connection to server got closed. Server will restart.
2023-10-13 16:17:35.249 [info] true
2023-10-13 16:17:35.249 [info] [Error - 16:17:35] Python Jedi client: couldn't create connection to server.
2023-10-13 16:17:35.249 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.249 [info] [Error - 16:17:35] Restarting server failed
2023-10-13 16:17:35.249 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.279 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-13 16:17:35.282 [info] [Error - 16:17:35] Server initialization failed.
2023-10-13 16:17:35.282 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.282 [info] [Error - 16:17:35] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-13 16:17:35.282 [info] [Error - 16:17:35] Python Jedi client: couldn't create connection to server.
2023-10-13 16:17:35.282 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-13 16:17:35.282 [info] [Error - 16:17:35] Restarting server failed
2023-10-13 16:17:35.282 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
