2023-10-12 18:52:52.107 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:52:52.138 [info] [Error - 18:52:52] Server initialization failed.
2023-10-12 18:52:52.138 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.138 [info] [Info  - 18:52:52] Connection to server got closed. Server will restart.
2023-10-12 18:52:52.138 [info] true
2023-10-12 18:52:52.138 [info] [Error - 18:52:52] Python Jedi client: couldn't create connection to server.
2023-10-12 18:52:52.138 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.160 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:52:52.160 [info] [Error - 18:52:52] Server initialization failed.
2023-10-12 18:52:52.160 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.160 [info] [Info  - 18:52:52] Connection to server got closed. Server will restart.
2023-10-12 18:52:52.160 [info] true
2023-10-12 18:52:52.161 [info] [Error - 18:52:52] Python Jedi client: couldn't create connection to server.
2023-10-12 18:52:52.161 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.192 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 18:52:52.192 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:52:52.197 [info] [Error - 18:52:52] Server initialization failed.
2023-10-12 18:52:52.197 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.197 [info] [Info  - 18:52:52] Connection to server got closed. Server will restart.
2023-10-12 18:52:52.197 [info] true
2023-10-12 18:52:52.197 [info] [Error - 18:52:52] Python Jedi client: couldn't create connection to server.
2023-10-12 18:52:52.197 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.197 [info] [Error - 18:52:52] Restarting server failed
2023-10-12 18:52:52.197 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.215 [info] Traceback (most recent call last):

2023-10-12 18:52:52.216 [info]   File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 18:52:52.216 [info]     from jedi_language_server.cli import cli

2023-10-12 18:52:52.216 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:52:52.219 [info] [Error - 18:52:52] Server initialization failed.
2023-10-12 18:52:52.219 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.219 [info] [Info  - 18:52:52] Connection to server got closed. Server will restart.
2023-10-12 18:52:52.219 [info] true
2023-10-12 18:52:52.219 [info] [Error - 18:52:52] Python Jedi client: couldn't create connection to server.
2023-10-12 18:52:52.219 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.219 [info] [Error - 18:52:52] Restarting server failed
2023-10-12 18:52:52.219 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.241 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli

2023-10-12 18:52:52.241 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 18:52:52.244 [info] [Error - 18:52:52] Server initialization failed.
2023-10-12 18:52:52.244 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.244 [info] [Error - 18:52:52] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-12 18:52:52.244 [info] [Error - 18:52:52] Python Jedi client: couldn't create connection to server.
2023-10-12 18:52:52.244 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 18:52:52.245 [info] [Error - 18:52:52] Restarting server failed
2023-10-12 18:52:52.245 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
