2023-10-12 21:38:45.358 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 21:38:45.359 [info]     from jedi_language_server.cli import cli

2023-10-12 21:38:45.360 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 21:38:45.451 [info] [Error - 21:38:45] Server initialization failed.
2023-10-12 21:38:45.451 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.451 [info] [Info  - 21:38:45] Connection to server got closed. Server will restart.
2023-10-12 21:38:45.451 [info] true
2023-10-12 21:38:45.451 [info] [Error - 21:38:45] Python Jedi client: couldn't create connection to server.
2023-10-12 21:38:45.452 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.492 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 21:38:45.495 [info] [Error - 21:38:45] Server initialization failed.
2023-10-12 21:38:45.495 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.495 [info] [Info  - 21:38:45] Connection to server got closed. Server will restart.
2023-10-12 21:38:45.495 [info] true
2023-10-12 21:38:45.495 [info] [Error - 21:38:45] Python Jedi client: couldn't create connection to server.
2023-10-12 21:38:45.495 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.535 [info] Traceback (most recent call last):

2023-10-12 21:38:45.536 [info]   File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 21:38:45.536 [info]     from jedi_language_server.cli import cli

2023-10-12 21:38:45.536 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 21:38:45.540 [info] [Error - 21:38:45] Server initialization failed.
2023-10-12 21:38:45.540 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.540 [info] [Info  - 21:38:45] Connection to server got closed. Server will restart.
2023-10-12 21:38:45.540 [info] true
2023-10-12 21:38:45.541 [info] [Error - 21:38:45] Python Jedi client: couldn't create connection to server.
2023-10-12 21:38:45.541 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.541 [info] [Error - 21:38:45] Restarting server failed
2023-10-12 21:38:45.541 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.579 [info] Traceback (most recent call last):

2023-10-12 21:38:45.582 [info]   File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 21:38:45.582 [info]     from jedi_language_server.cli import cli

2023-10-12 21:38:45.583 [info] ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 21:38:45.586 [info] [Error - 21:38:45] Server initialization failed.
2023-10-12 21:38:45.586 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.586 [info] [Info  - 21:38:45] Connection to server got closed. Server will restart.
2023-10-12 21:38:45.586 [info] true
2023-10-12 21:38:45.587 [info] [Error - 21:38:45] Python Jedi client: couldn't create connection to server.
2023-10-12 21:38:45.587 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.587 [info] [Error - 21:38:45] Restarting server failed
2023-10-12 21:38:45.587 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.612 [info] Traceback (most recent call last):
  File "/home/megame/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-12 21:38:45.613 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-12 21:38:45.618 [info] [Error - 21:38:45] Server initialization failed.
2023-10-12 21:38:45.618 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.618 [info] [Error - 21:38:45] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-12 21:38:45.618 [info] [Error - 21:38:45] Python Jedi client: couldn't create connection to server.
2023-10-12 21:38:45.618 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-12 21:38:45.618 [info] [Error - 21:38:45] Restarting server failed
2023-10-12 21:38:45.618 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
